server:
  port: 8080 # ?? ??(???? 8080)
spring:
  thymeleaf:
    cache: false # ???? ?? ??
    prefix: file:src/main/resources/templates/ # ???? ?? ??(? ??? ?? ??)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/basic1__dev?useSSL=false&serverTimezone=UTC
    username: lldj
    password: lldj123414
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # DB ??? ????(??? ???? ??? ?)
